// <auto-generated />
using System;
using EFCoreForRazorPages.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreForRazorPages.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20221022010913_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96"),
                            Abbreviation = "Stf",
                            Description = "People who work in school but not teaching",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d"),
                            Abbreviation = "Fct",
                            Description = "People who teach in school",
                            Name = "Faculty"
                        },
                        new
                        {
                            Id = new Guid("1fb7085a-762f-440c-87de-59f75f85e935"),
                            Abbreviation = "Std",
                            Description = "People who learn in school",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            DateOfBirth = new DateTime(2022, 10, 22, 9, 9, 13, 346, DateTimeKind.Local).AddTicks(2244),
                            EmailAddress = "avengeant@mailinator.com",
                            Gender = 1,
                            Name = "Ajani",
                            RoleId = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            DateOfBirth = new DateTime(2022, 10, 22, 9, 9, 13, 346, DateTimeKind.Local).AddTicks(2256),
                            EmailAddress = "lvess@mailinator.com",
                            Gender = 2,
                            Name = "Liliana",
                            RoleId = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            DateOfBirth = new DateTime(2022, 10, 22, 9, 9, 13, 346, DateTimeKind.Local).AddTicks(2259),
                            EmailAddress = "ktide@mailinator.com",
                            Gender = 2,
                            Name = "Kiora",
                            RoleId = new Guid("1fb7085a-762f-440c-87de-59f75f85e935")
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.HasOne("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
