// <auto-generated />
using System;
using EFCoreForRazorPages.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreForRazorPages.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20230114031217_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96"),
                            Abbreviation = "Stf",
                            Description = "People who work in school but not teaching",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d"),
                            Abbreviation = "Fct",
                            Description = "People who teach in school",
                            Name = "Faculty"
                        },
                        new
                        {
                            Id = new Guid("1fb7085a-762f-440c-87de-59f75f85e935"),
                            Abbreviation = "Std",
                            Description = "People who learn in school",
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("1fb7085a-762f-440c-87de-59f75f85e934"),
                            Abbreviation = "Adm",
                            Description = "Admin",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            DateOfBirth = new DateTime(2023, 1, 14, 11, 12, 16, 575, DateTimeKind.Local).AddTicks(6781),
                            EmailAddress = "avengeant@mailinator.com",
                            Gender = 1,
                            Name = "Ajani",
                            RoleId = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            DateOfBirth = new DateTime(2023, 1, 14, 11, 12, 16, 689, DateTimeKind.Local).AddTicks(3091),
                            EmailAddress = "lvess@mailinator.com",
                            Gender = 2,
                            Name = "Liliana",
                            RoleId = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            DateOfBirth = new DateTime(2023, 1, 14, 11, 12, 16, 804, DateTimeKind.Local).AddTicks(1316),
                            EmailAddress = "ktide@mailinator.com",
                            Gender = 2,
                            Name = "Kiora",
                            RoleId = new Guid("1fb7085a-762f-440c-87de-59f75f85e935")
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.UserLogin", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3fa581e-e674-48ee-a589-2b59f2d9a71f"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "$2a$11$wVrXuBep6CiMXT7HX3JHMOLnw78eLiaUa8iXSZDPmXmQZT4hHGfE."
                        },
                        new
                        {
                            Id = new Guid("0eba2a2b-55d7-4423-9cc5-0109eb20a0b7"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("33d52442-4554-4dbb-b468-68f2dcb6e4dc"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("72c24816-f32d-4f7f-8824-073007663e6b"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "$2a$11$/SIKSaNDvZTZyfzisN3ZeuDxUFs6NfGDn0mg5EsLWy1H4nc/4u9aK"
                        },
                        new
                        {
                            Id = new Guid("550bca90-ede0-4c47-84a4-332a0f330ee7"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("8318e258-7292-4386-9b5e-c853e9b8eca8"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("62091306-2013-4d1d-b7a0-a215b1f48d7c"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "$2a$11$uyvSQcY9dawfoS2cWZMyPejVxz8iG32NapPEXEeTGpRRi5Dd27XSq"
                        },
                        new
                        {
                            Id = new Guid("cc56c16e-3c4e-406d-bb22-9fb7ca1be801"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("584a815f-3243-4b57-b902-b14a1f48f265"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "0"
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ec7711c-3457-4fad-9b34-68f87258fd9b"),
                            RoleId = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96"),
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0")
                        },
                        new
                        {
                            Id = new Guid("f0fbb9d4-abc3-4666-a775-cbe476b3bb7e"),
                            RoleId = new Guid("1fb7085a-762f-440c-87de-59f75f85e934"),
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1")
                        },
                        new
                        {
                            Id = new Guid("4a6dde45-2a1a-4c31-8e70-0bf2df844da4"),
                            RoleId = new Guid("1fb7085a-762f-440c-87de-59f75f85e935"),
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2")
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.HasOne("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.UserRole", b =>
                {
                    b.HasOne("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("EFCoreForRazorPages.Infrastructure.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
