// <auto-generated />
using System;
using EFCoreForRazorPages.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreForRazorPages.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20230107021706_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96"),
                            Abbreviation = "Stf",
                            Description = "People who work in school but not teaching",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d"),
                            Abbreviation = "Fct",
                            Description = "People who teach in school",
                            Name = "Faculty"
                        },
                        new
                        {
                            Id = new Guid("1fb7085a-762f-440c-87de-59f75f85e935"),
                            Abbreviation = "Std",
                            Description = "People who learn in school",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            DateOfBirth = new DateTime(2023, 1, 7, 10, 17, 6, 340, DateTimeKind.Local).AddTicks(651),
                            EmailAddress = "avengeant@mailinator.com",
                            Gender = 1,
                            Name = "Ajani",
                            RoleId = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            DateOfBirth = new DateTime(2023, 1, 7, 10, 17, 6, 458, DateTimeKind.Local).AddTicks(2468),
                            EmailAddress = "lvess@mailinator.com",
                            Gender = 2,
                            Name = "Liliana",
                            RoleId = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96")
                        },
                        new
                        {
                            Id = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            DateOfBirth = new DateTime(2023, 1, 7, 10, 17, 6, 578, DateTimeKind.Local).AddTicks(7146),
                            EmailAddress = "ktide@mailinator.com",
                            Gender = 2,
                            Name = "Kiora",
                            RoleId = new Guid("1fb7085a-762f-440c-87de-59f75f85e935")
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.UserLogin", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06be8cb4-02de-4ab1-b574-49e017f5b255"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "$2a$11$.yd9h52TEt7R/Yi4ten5y.AkYhkQACzGTda18xpQt0j3vg2I0VXoK"
                        },
                        new
                        {
                            Id = new Guid("c6ea7aa9-e127-4c48-ab51-380422dc16a3"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("11a37b16-c08f-40b6-bb2b-402fe0540d2b"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac0"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("3b39a47d-2d91-4f7d-9fe5-e355c0f02b23"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "$2a$11$hI.W3KNJb2Vh2dknAr94luGYJK/bHO5DjmVBUWPOgokuiDGxVFD3O"
                        },
                        new
                        {
                            Id = new Guid("bed461fb-3563-46fc-9071-53f01bf6a311"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("869de353-8700-4fa7-a305-23be87620815"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac1"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("8e147fd8-4606-4420-a69c-56ac9e7c92ab"),
                            Key = "Password",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "$2a$11$rcJcAXC43E88gnsl0kwssOntWGgyCR/hfg.C8QJjut8CDgH0lXrPS"
                        },
                        new
                        {
                            Id = new Guid("2a1ba526-1cf0-4672-8a9b-0dec239eb31c"),
                            Key = "IsActive",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("7b2b9f86-2dfd-442f-b859-0746e6fb6ca6"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2"),
                            Value = "0"
                        });
                });

            modelBuilder.Entity("EFCoreForRazorPages.Infrastructure.Domain.Models.User", b =>
                {
                    b.HasOne("EFCoreForRazorPages.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
